<div class="padder">
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <div class="page-head">
        <h3><?php echo $this->__('RMA Created Successfully') ?></h3>
    </div>
    <div>
		<?php echo $this->__('Your RMA has been succesfully submitted. <br/>
        Our customer service department will be contacting you regarding your RMA.<br/>
        Any updates on your RMA can be viewed by logging into your account and going to "My RMA". <br/>'); ?>
    </div>

</div>