<div class="padder">
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_rmas = $this->getRmas(); ?>
<?php 
	//$_rmas->setPageSize(1);
    //$_rmas->setCurPage(1);
?>
<div class="page-head button-level">
    <h3><?php echo $this->__('My RMAs') ?></h3>
</div>
    <a href="<?php echo $this->getUrl('rma/pickorder') ?>" style="font-size: 16px;"><?php echo $this->__('File New RMA'); ?></a>

<?php if($_rmas->getSize()): ?>
<table cellspacing="0" class="data-table" id="my-orders-table" style="margin-top: 10px;">
    <thead>
        <tr>
            <th><?php echo $this->__('Date Filed') ?></th>
            <th><?php echo $this->__('Order #') ?></th>
            <th><?php echo $this->__('RMA #') ?></th>
            <th class="a-center"><?php echo $this->__('Items') ?></th>
            <th><?php echo $this->__('RMA Status') ?></th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php $_odd = ''; ?>
        <?php foreach ($_rmas as $_rma): ?>
             <tr>
                <td>
         	    <?php echo date('M d, Y', strtotime($_rma->getDateCreated()) - (8*60*60))?>
                </td>
                <td><?php echo $_rma->getOrderNumber()?></td>
                <td><?php
                
					 $thisRMANum = $_rma->getRmaNumber();
					 if($thisRMANum == ""){ echo("---"); }
					 echo($thisRMANum);
					 
					 ?></td>
                <td class="a-center"><?php
					 
					$amount = 0;
					
					unset($itemIDs);
					$itemIDs = array();
					unset($qty);
					$qty = array();
					foreach( $_rma->getItemsCollection() as $item )
						{
						$qty[$item->getItemId()] = $item->getQty();
						$itemIDs[$item->getItemId()] = $item->getItemId();
						}
					
					
					$thisOrderId = $_rma->getOrderId();
					$order_model = Mage::getModel('sales/order')->load($thisOrderId);
					$allItems = $order_model->getItemsCollection();
					
					foreach( $allItems as $itm )
						{
						$thisProductId = $itm->getProductId();
						$thisPrice = $itm->getPrice();
						
						if(in_array($thisProductId, $itemIDs))
							{
							$amount += $qty[$thisProductId];
							}
						}
                
					 echo($amount);
					 
					 ?></td>
                <td><em><?php echo $_rma->getStatus()?></em></td>
                <td><a href="<?php echo $this->getUrl( '*/view', array( 'id' => $_rma->getId() ) )?>"><?php echo $this->__('View RMA'); ?></a></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('my-orders-table')</script>
<?php echo $this->getPagerHtml(); ?>
<?php else: ?>
<div class="padder"> <p><?php echo $this->__('You have placed no RMA(s).'); ?></p></div>
<?php endif ?>

</div>

            <?php
                
                /*
                    This shows how to load specific fields from a record in the database.
                    1) Note the load(15), this corresponds to saying "select * from table where table_id = 15"
                    2) You can then just use the get(fieldname) to pull specific data from the table.
                    3) If you have a field named news_id, then it becomes getNewsId, etc.
                */
                
                /*$news = Mage::getModel('rma/rma')->load(3);
                echo $news->getNewsId();
                echo $news->getTitle();
                echo $news->getContent();
                echo $news->getStatus();
				echo $news->getFilename();
                */
                
                /*
                    This shows an alternate way of loading datas from a record using the database the "Magento Way" (using blocks and controller).
 					Uncomment blocks in /app/code/local/Namespace/Module/controllers/IndexController.php if you want to use it.

               */
                
               /* $object = $this->getRma();
                echo 'id: '.$object['rma_number'].'<br/>';
				echo 'content: '.$object['remarks'].'<br/>';
				echo 'status: '.$object['status'].'<br/>';
                 */          
            
            
                /*
                    This shows how to load multiple rows in a collection and save a change to them.
                    1) The setPageSize function will load only 5 records per page and you can set the current Page with the setCurPage function.
                    2) The $collection->walk('save') allows you to save everything in the collection after all changes have been made.
                */
                
                /*$i = 0;
                
                $collection = Mage::getModel('rma/rma')->getCollection();
                $collection->setPageSize(5);
                $collection->setCurPage(2);
                $size = $collection->getSize();
                $cnt = count($collection);
                foreach ($collection as $item) {
                    $i = $i+1;
                    $item->setTitle($i);
                    echo $item->getTitle();
                }

                $collection->walk('save');
                */
                
                /*
                    This shows how to load a single record and save a change.
                    1) Note the setTitle, this corresponds to the table field name, title, and then you pass it the text to change.
                    2) Call the save() function only on a single record.
                */
                /*
                $object = Mage::getModel('rma/rma')->load(1);
                $object->setTitle('This is a changed title');
                $object->save();
				*/

            ?> 